app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
user_employer_registration:
    path:  /register/employer
    defaults: { _controller: AppBundle:RegistrationUserEmployer:register }

user_two_registration:
    path:  /register/jobseeker
    defaults: { _controller: AcmeUserBundle:RegistrationUserSeeker:register }