# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    authentication.handler.login_success_handler:
        class: AppBundle\Security\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker']

    app.registration_confirmed_subscriber:
        class: AppBundle\EventSubscriber\RegistrationConfirmedSubscriber
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }